Fix encoding of paths
We saw the script fail with this error when running against PP Production:

    UnicodeEncodeError: 'ascii' codec can't encode character u'\u8ca0' in
position 37: ordinal not in range(128)

The error happened when we were trying to request pageview data for a path
returned in an earlier response, and came from:

    https://github.com/alphagov/performanceplatform-client.py/blob/36e82af925bfbc0e3115036b54bd349f676b0c5a/performanceplatform/client/base.py#L134

Paths in PP responses are UTF8-encoded, so we need to handle them as such to
avoid encoding errors when using them in query params to request pageview data
later on.